[package]
name = "lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lspower = "1.5.0"

[dependencies.dbt-jinja-parser]
path = "../jinja_parser"